name: update-data

on:
  # allows running this workflow manually
  workflow_dispatch:

jobs:
  update_data:
    name: update-data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: npm install
      - name: Clear cache
        run: npm run clear-cache
      - name: Download data
        run: npm run download-data
      - name: Extract data
        run: sudo npm run extract-data
      - name: Run project
        run: npm run start
      - name: Copy data
        run: npm run copy-data
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/
          publish_branch: data
          force_orphan: true
          enable_jekyll: true
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fortnite-json
          path: ./cache/fortnite.json
